### ISSUE TITLE
.env не должен попадать в репозиторий

### ISSUE THREAD

**Issue by mike-hammer** [mo3g666/project-x#1]
Файл `.env` содержит настройки текущего локального окружения. Например, параметры подключения к серверу бд. Локально у разработчика они будут отличаться от значений на проде (даже между собой у разработчиков они будут разные). Поэтому правильным подходом считается не коммитить его в репозиторий.

Можно сделать так: переименовать `.env` в `.env.dist`. Сам  `.env` добавить в `.gitignore`. Соответственно в репозитории будет храниться только `.env.dist` со всеми необходимыми параметрами и демо значениями. Когда проект где-то разворачивается в первый раз (не важно локально у разраба или на проде), то нужно .env.dist скопировать в .env и наполнить реальными значениями. Таким образом .env будет содержать нужные значения и никогда не подает в репозиторий.

Также нужно обновить README и добавить туда шаг с созданием .env

Возможно пакет dotenv дает какие-то инструменты по автоматизации этого процесса. Можно поресерчить.

**Comment by mo3g666** [comment]
> Файл `.env` содержит настройки текущего локального окружения. Например, параметры подключения к серверу бд. Локально у разработчика они будут отличаться от значений на проде (даже между собой у разработчиков они будут разные). Поэтому правильным подходом считается не коммитить его в репозиторий.
> 
> Можно сделать так: переименовать `.env` в `.env.dist`. Сам `.env` добавить в `.gitignore`. Соответственно в репозитории будет храниться только `.env.dist` со всеми необходимыми параметрами и демо значениями. Когда проект где-то разворачивается в первый раз (не важно локально у разраба или на проде), то нужно .env.dist скопировать в .env и наполнить реальными значениями. Таким образом .env будет содержать нужные значения и никогда не подает в репозиторий.
> 
> Также нужно обновить README и добавить туда шаг с созданием .env
> 
> Возможно пакет dotenv дает какие-то инструменты по автоматизации этого процесса. Можно поресерчить.

`.env`  уже находится в `.gitignore` и был добавлен в обход этого правила с шаблонным значением. [https://github.com/mo3g666/project-x/blob/b8d65dd10f9c242e34706d52ab9c3bf5eaea2636/.gitignore#L71-L73](url)

Я переименую его в `.env.dist` и исправлю README.
