### ISSUE TITLE
Prisma Issue

### ISSUE THREAD

**Issue by leonardssh** [mo3g666/project-x#18]
Hey, I saw that you want to use Prisma, but I want to make your day and let you know that Prisma does not work in the RAGE environment. More specifically, on the linux side. On windows it works without problems, but on linux it doesn't.

The same problem is with all libraries that need C++ or Rust.

e.g 
[bcrypt](https://www.npmjs.com/package/bcrypt) <--- doesn't work
[bcryptjs](https://www.npmjs.com/package/bcryptjs) <--- works!

**Comment by mo3g666** [comment]
@leonardssh
Unfortunately I'm replying to this topic quite late, but I fixed this problem when I was working on an alt:V project, and now I can confidently say that Prisma ORM works in RageMP under Linux )

**Comment by leonardssh** [comment]
Did you make any changes, or did it fixed itself out by RAGE:MP? Have you tested [bcrypt](https://www.npmjs.com/package/bcrypt)?

**Comment by mo3g666** [comment]
> 
For Prisma ORM to work, it is necessary to specify in the schema file
```js
generator client {
    provider   = "prisma-client-js"
    engineType = "binary"
}`
I don't remember about bcrypt anymore, but I think I replaced it with bcryptjs

**Comment by mo3g666** [comment]
@leonardssh
For Prisma ORM to work, it is necessary to specify in the schema file
```js
generator client {
    provider   = "prisma-client-js"
    engineType = "binary"
}
```
I don't remember about bcrypt anymore, but I think I replaced it with bcryptjs
